/*
==========================================================
                Magnitude Analysis
==========================================================
*/

-- Find total customers by countries
SELECT
	country,
	SUM(DISTINCT customer_id) AS total_customers
FROM 
	gold.dim_customer
GROUP BY country
ORDER BY total_customers   DESC;

-- Find total customers by genders
SELECT
	gender,
	SUM(DISTINCT customer_id) AS total_customers
FROM 
	gold.dim_customer
GROUP BY gender;

-- Find total products by category
SELECT 
	category,
	COUNT(DISTINCT product_id) AS total_products
FROM 
	gold.dim_product
GROUP BY category ;

-- what is the average cost in each category
SELECT 
	category,
	AVG(product_cost) AS average_cost	
FROM 
	gold.dim_product
GROUP BY category
ORDER BY AVG(product_cost) DESC;

-- Find total revenue generated by each customer
SELECT 
	CONCAT(dc.first_name," ", dc.last_name ) AS customer_name,
	SUM(sales_amount) AS total_sales
FROM
	gold.fact_sales fs 
LEFT JOIN gold.dim_customer dc
ON 
	dc.customer_key = fs.customer_key 
GROUP BY CONCAT(dc.first_name," ", dc.last_name );

-- What is the distribution of total items sold per country
SELECT
	dc.country ,
	SUM(fs.quantity  ) as items_sold_per_country
FROM
	gold.fact_sales fs,
	gold.dim_customer dc
WHERE
	dc.customer_key = fs.customer_key 
GROUP BY country;
